FROM balenalib/%%BALENA_MACHINE_NAME%%-node

# Install dependencies
RUN install_packages build-essential

WORKDIR /usr/src/app

# This will copy all files in our root to the working  directory in the container
COPY . ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

# server.js will run when container starts up on the device
CMD ["/bin/bash", "/usr/src/app/start.sh"]