# Use provided environment variables or defaults.
WIDTH=${WIDTH:=1280}
HEIGHT=${HEIGHT:=720}
INTRA_REFRESH_PERIOD=${INTRA_REFRESH_PERIOD:=60}
FLIP_HORIZONTAL=${FLIP_HORIZONTAL:=""}
FLIP_VERTICAL=${FLIP_VERTICAL:=""}
ROTATION=${ROTATION:=0}
FRAMES_PER_SECOND=${FRAMES_PER_SECOND:=30}
BITRATE=${BITRATE:=2500000}
METERING_MODE=${METERING_MODE:="average"}
EXPOSURE_MODE=${EXPOSURE_MODE:="fixedfps"}

echo "Starting raspivid..."
raspivid -n -t 0 -w $WIDTH -h $HEIGHT -g $INTRA_REFRESH_PERIOD $FLIP_HORIZONTAL $FLIP_VERTICAL -rot $ROTATION -fps $FRAMES_PER_SECOND -b $BITRATE -mm $METERING_MODE -ex $EXPOSURE_MODE -ih -pf high -o udp://$STREAM_DESTINATION_IP:$STREAM_DESTINATION_PORT